export const data = [
    { auto: "audi-1" },
    { auto: "audi-2" },
    { auto: "audi-3" },
    { auto: "audi-a3" },
    { auto: "audi-a4" },
    { auto: "audi-a5" },
    { auto: "audi-a6" },
    { auto: "audi-quatro" },
    { auto: "audi-quatro-2d" },
    { auto: "bmw-1" },
    { auto: "bmw-2" },
    { auto: "bmw-13" },
    { auto: "bmw-m3" },
    { auto: "bmw-a5" },
    { auto: "bmw-34" },
    { auto: "bmw-jh3" },
    { auto: "kia-1" },
    { auto: "kia-22" },
    { auto: "kia-3" },
    { auto: "kia-4" },
    { auto: "kia-5" },
    { auto: "kia-6" },
    { auto: "kia-7" },
    { auto: "kia-100" },
];
